language: node_js
node_js:
  - "stable"
  - "4.2"

sudo: false

script:
  - "npm run test-coverage"
after_script:
  - "npm install coveralls@2 && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
