language: node_js
node_js:
  - "latest"
  - "4.x"
  - "0.12"
  - "0.10"

sudo: false

script:
  - "npm run test-coverage"
after_script:
  - "npm install coveralls@2 && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
